### ISSUE TITLE
Setup: required content

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/reproducible-tinynews-content-api#31]
Now that I've deployed & killed & deployed the content API several times, trying to work with it via the Google Docs add-on, I think we will need to populate some content when we set it up.

### definitely:

* categories/sections
* homepage layout schemas

### possibly?

* authors (can be done in the tinycms, sure, and i think the google add-on creates authors - doublecheck)
* placeholder article?
* homepage data using placeholder article? otherwise the homepage looks strange. perhaps a better way to handle this is to use a placeholder homepage with info on how to remove it (publish an article; config the homepage, publish the homepage)

**Comment by jacqui** [comment]
# homepage layouts

## query

```graphql
 mutation CreateHomepageLayoutSchema($data: HomepageLayoutSchemaInput!) {
    homepageLayoutSchemas {
        createHomepageLayoutSchema(data: $data) {
          data {
            id
            name
            data
          }
          error  {
        		code
        		message
        		data
    			}
        }
    }
}
```

## variables: big featured story

```
{
  "data": {
    "name": "Big Featured Story",
    "data": "{ \"featured\":\"string\" }"
  }
}
```

## variables: large package story lead

```
{
  "data": {
    "name": "Large Package Story lead",
    "data": "{ \"featured\":\"string\", \"subfeatured-left\":\"string\",  \"subfeatured-middle\":\"string\",\"subfeatured-right\":\"string\"}"
  }
}
```

**Comment by jacqui** [comment]
So far I've found a couple of ways to populate content:

1. the sort of documented commodo way, [mentioned in passing in the "crash course"](https://docs.webiny.com/docs/api-development/commodo/crash-course/)
2. in the graphql playground
3. via curl / node / etc using the graphql api

From what I've seen of the first approach, I think we need to use the graphql API directly instead. Using commodo's `populate` and `save` functions works, but it's unclear when this code gets executed and how many times it is run. I found it trying to recreate the data over and over; one deployment, before I added a unique constraint, created 6 of each record. Then there's the question of how to configure this per-TNC client.

I'm now leaning towards something a bit more controlled and interactive. One thing I didn't mention about the commodo approach is that it happens during deployment and there's absolutely no indication of whether or not it was run or even worked 🤷‍♀️ 

That leaves:
* a command line tool that you or I could run - or -
* a slimmed down web admin, like part of the `tinycms` that's not linked or made accessible by default

I started writing some scripts in a `populate/` directory next to the `tinynews-models` in this repo, using [commander](https://github.com/tj/commander.js) and [inquirer](https://github.com/SBoudrias/Inquirer.js/) as I've never used node.js for anything command line. It's very easy, and it wouldn't take much for me to finish this if it's the way we want to go.

* `category.js` - `./category.js --host https://d3qwqlmif92l4j.cloudfront.net/graphql --pat 7bd7ce3f3a8761ca539d2818d99576935b0e0d95e6c5d065 --localeID 5f8cc4e3751f9c0008360e7f then prompts for each category title/slug
* `homepage.js` - populates the 2 standard layout options we've been using

However, I think the web admin will be simpler. We could then look up the localeID and already have the PAT (personal access token) and host (graphql API) be set. I mean, we will need to configure this stuff anyway. I guess I'm convincing myself as I type this 😉

What do you think of all this @TylerFisher ?

**Comment by TylerFisher** [comment]
It makes sense to me that population/bootstrapping the DB would be a separate step from creating the tables. This way, if we do make changes to the database and have to redeploy to already live databases, we aren't trying to recreate old model objects (I know the `beforeCreate` checks would catch them, but still). 

I think the tough thing about putting the admin at a `tinycms/` URL is it creates a chicken and egg situation. How do you set up the admin if we haven't even deployed the next.js site yet? Or is the workflow like:

1. create the database
2. get PAT from admin
3. deploy next.js site with new keys
4. log into tinycms, populate database

**Comment by jacqui** [comment]
Hey we discussed this on slack, but I know I'll forget this if I look at this issue in the future, so here goes:

- yes there could be a chicken & egg situation, but...
- if we look at this as part of the required setup for the frontend + tinycms that has to happen anyway...
- after getting PAT from the admin, we need to configure the site & deploy it
- then log into tinycms, set the site content for homepage layouts, categories and site metadata
