### ISSUE TITLE
Sync Webiny deployment state on S3

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/reproducible-tinynews-content-api#69]
In order to predictably keep the same deployment locations for different environments, we should sync the deployment state to an S3 bucket as part of the deployment process.

This probably means writing a custom script that:

1. Pulls state from s3
2. Deploys webiny based on that state
3. Pushes new state to s3

This functionality could also work as part of a CI integration like Github Actions. That's probably a good idea for the future, but let's make sure this S3 sync idea works first.

**Comment by jacqui** [comment]
Okay, I think I've figured out how to do this. I've borrowed much of the specifics of the approach to [the example the webiny folks mentioned](https://github.com/oev-berlin/aws-cdk-webiny-deployment-pipeline).

- [x] (initial setup task) create 2 buckets per environment. In our case, this will mean we're creating 2 buckets per Tiny News Org; we should be wary of hitting an s3 bucket limit and pre-emptively ask for it to be increased.
  - tinynewsplatform-state-bucket-$env example `tinynewsplatform-state-bucket-prod`
  - tinynewsplatform-state-environment-$env example `tinynewsplatform-environment-bucket-prod`
- [x] (initial setup task) upload initial versions of files to both buckets; repladce `prod` with actual `$ENVIRONMENT`
  - `aws s3 cp api/.env.json "s3://tinynewsplatform-environment-bucket-prod/api.env.json"`
  - `aws s3 cp .env.json "s3://tinynewsplatform-environment-bucket-prod/root.env.json"`
  - `aws s3 cp .webiny s3://tinynewsplatform-state-bucket-prod/ --recursive`
- [x] (on each deploy) download files from s3
  -  `aws s3 cp s3://tinynewsplatform-state-bucket-prod/ .webiny --recursive`
  - `aws s3 cp "s3://tinynewsplatform-environment-bucket-prod/api.env.json" api/.env.json`
  - `aws s3 cp "s3://tinynewsplatform-environment-bucket-prod/root.env.json" .env.json`
- [x] (required also on each deploy? first deploy only? not at all?) run `yarn`
  - `answer: probably a good idea to run it if only to catch any errors, updates`
- [x] (on each deploy) run the webiny deploy command as before
  - `yarn webiny deploy api --env=prod` # replace `prod` with actual `$ENVIRONMENT`
- [x] local webiny state files will have changed on deploy, so we should sync them back up to s3 along with the env files
  - `aws s3 cp api/.env.json "s3://tinynewsplatform-environment-bucket-prod/api.env.json"`
  - `aws s3 cp .env.json "s3://tinynewsplatform-environment-bucket-prod/root.env.json"`
  - `aws s3 cp .webiny s3://tinynewsplatform-state-bucket-prod/ --recursive`
- [x] test the above all works running these commands manually on the CLI
- [x] script the above and test locally: yarn sync-deploy
  - script should have two sub-commands:
  - `setup`: create 2 private s3 buckets; initial push of files
  - `deploy`: download files from s3; yarn; yarn webiny deploy; upload files to s3
- [ ] setup CI for the api?
